#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Mon Nov 03 13:45:21 CET 2025
maven-metadata-areaCentrosEducativos-snapshot.xml.error=
maven-metadata-areaCentrosEducativos-snapshot.xml.lastUpdated=1762173921455
maven-metadata-snapshots.xml.lastUpdated=1762173921450
