afirma.integrator.host=ws233.juntadeandalucia.es
afirma.integrator.versionAfirma=6
afirma.integrator.rutaAlmacenCert=trustkeystore_afv5
afirma.integrator.claveAlmacenCert=changeit
afirma.integrator.idApp=iaap.GALATEA
afirma.integrator.user=iaap.galatea
afirma.integrator.password=FE9XZJglHy
afirma.certificado.pruebas=
afirma.parametros.algoritmoHash=SHA256
afirma.parametros.formatoFirma=CAdES
afirma.parametros.modoFirmaXML=ENVELOPING