#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Mon Nov 03 13:45:24 CET 2025
maven-metadata-areaCentrosEducativos-snapshot.xml.lastUpdated=1762173924346
maven-metadata-snapshots.xml.lastUpdated=1762173924343
