#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Mon Nov 10 10:54:30 CET 2025
maven-metadata-areaCentrosEducativos-release.xml.error=
maven-metadata-areaCentrosEducativos-release.xml.lastUpdated=1762768470363
maven-metadata-areaCentrosEducativos-snapshot.xml.error=
maven-metadata-areaCentrosEducativos-snapshot.xml.lastUpdated=1762768470366
maven-metadata-central.xml.lastUpdated=1762768470358
maven-metadata-snapshots.xml.lastUpdated=1762768470361
